[default_session]
# Startup with terminal and nvim open
#startup_command = "tmux split-window -h 'nvim .' && clear && tmux run-shell '~/.tmux/plugins/tmux-agent-sidebar/bin/tmux-agent-sidebar toggle \"#{window_id}\" \"#{pane_current_path}\"' && clear"
## Startup with Claude + nvim open
#startup_command = "tmux send-keys 'claude' Enter && tmux split-window -h 'nvim .' && tmux run-shell '~/.tmux/plugins/tmux-agent-sidebar/bin/tmux-agent-sidebar toggle \"#{window_id}\" \"#{pane_current_path}\"'"
