#!/bin/bash

source "$CONFIG_DIR/colors.sh"

ITEMS_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="JetBrainsMono Nerd Font" # also needs SF Pro for icons
PADDINGS=6

bar=(
  height=45
  color=$BAR_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=16
  padding_left=16
  y_offset=-5
  margin=-2
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:16.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=4
  label.font="$FONT:Bold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=2
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
)
#
sketchybar --default "${defaults[@]}"

source "$ITEMS_DIR/apple.sh"
source "$ITEMS_DIR/spotify.sh"

BRACKET_BG=(
  background.color=$BACKGROUND_1
  background.border_color=$BACKGROUND_2
  background.border_width=2
  background.corner_radius=9
)

# Right side grouped with bracket boxes
source "$ITEMS_DIR/clock.sh"
sketchybar --add bracket group_clock utcclock clock \
           --set group_clock "${BRACKET_BG[@]}"

source "$ITEMS_DIR/volume.sh"
source "$ITEMS_DIR/battery.sh"
sketchybar --add bracket group_status volume battery \
           --set group_status "${BRACKET_BG[@]}"

source "$ITEMS_DIR/cpu_mem.sh"
sketchybar --add bracket group_cpu cpu mem \
           --set group_cpu "${BRACKET_BG[@]}"

sketchybar --update
