#!/bin/bash

source "$CONFIG_DIR/colors.sh"

ITEMS_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="JetBrainsMono Nerd Font" # also needs SF Pro for icons
PADDINGS=3

bar=(
  height=45
  color=$BAR_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-5
  margin=-2
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:17.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Bold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
)
#
sketchybar --default "${defaults[@]}"

source "$ITEMS_DIR/apple.sh"
source "$ITEMS_DIR/spotify.sh"
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/volume.sh"
source "$ITEMS_DIR/battery.sh"

sketchybar --update
